### ISSUE TITLE
Export permissions only for 1 selected user

### ISSUE THREAD

**Issue by worldsdream** [JBines/Get-RecipientPermissions.ps1#2]
I want to get all the information of one selected user. 

I did run the command:
.\Get-RecipientPermissions.ps1 -Identity user -ExportCSV

The above command worked. I can see who that user has permissions on. 

But I would like to see. Who has access to the user account. 

What would be the right command to have them both in the csv export?

The command should run the whole organization, right?

$AllUsers = Get-Recipient -ResultSize 'Unlimited' ; $AllUsers | .\Get-RecipientPermissions.ps1 -ExportCSV

The above command is not what I am looking for. This will give me an output of the whole organization. 

I just want the single user. 

Thank you.

**Comment by JBines** [comment]
Unfortunately you need to first run this over the complete org. See here for the full write up https://practical365.com/migration/preliminary-permission-clean-up-steps-for-a-successful-mailbox-migration/
